### ISSUE TITLE
Block comment

### ISSUE THREAD

**Issue by Yajo** [hlamer/enki#193]
Please add a menu item and shortcut to (un)comment lines.

**Comment by dglent** [comment]
This feature should be implemented in 15.11.0 or later ?

**Comment by hlamer** [comment]
I've done basic implementation which supports `#` and `//` for the most popular languages.
Guys, could you test and give some feedback?

**Comment by hlamer** [comment]
I use and like it. Closing

**Comment by bjones1** [comment]
Aargh. I thought I'd posted on this, and even had a nice example of a fix, but must have not clicked the comment button. I'll re-create.

**Comment by bjones1** [comment]
When I hilight a block of text to comment out:

![image](https://cloud.githubusercontent.com/assets/2125584/13955489/d921927e-f012-11e5-822d-7a42d504ac15.png)

then press Ctrl+U, I expect only the hilighted lines to be commented out.

![image](https://cloud.githubusercontent.com/assets/2125584/13955527/fe85b900-f012-11e5-899e-2359ea5ef35e.png)

However, I see that an extra line at the end was commented out, the hilight on the first line was moved to only include the \n at the end of the line, and the hilight extended on the line line to include the entire line. I'd expect similar behavior to pressing Tab:

![image](https://cloud.githubusercontent.com/assets/2125584/13955570/27af4530-f013-11e5-863d-a924d077f300.png)

Except, of course, that comment characters are inserted instead of spaces.

**Comment by bjones1** [comment]
Another problem: if I open an unsupported file type (.s -- assembly, in my case), Ctrl-U applies Python-style commenting. This should be disabled for unsupported languages. Before:

![image](https://cloud.githubusercontent.com/assets/2125584/13955722/c788f59c-f013-11e5-97df-ecfd02f54b20.png)

After:

![image](https://cloud.githubusercontent.com/assets/2125584/13955745/da46600c-f013-11e5-960b-7adc9817a4c1.png)

**Comment by hlamer** [comment]
@bjones1, check master now

**Comment by bjones1** [comment]
The first problem looks much better. I still see the second case (in a non-Python or C file, Ctrl-U adds the wrong style of comment).

**Comment by bjones1** [comment]
Another bug, or perhaps a question: what should Ctrl-U do with mixed comments? My assumption is that it would comment them, uncommenting only it there are already comments everywhere.

I have this:
![image](https://cloud.githubusercontent.com/assets/2125584/14020800/b941bbce-f1a6-11e5-86e7-715c997543ed.png)

I'd like to comment it out, so I press Ctrl-U. But it's partially uncommented instead:
![image](https://cloud.githubusercontent.com/assets/2125584/14020832/d2e5417c-f1a6-11e5-9d45-9b2637b5db51.png)

**Comment by hlamer** [comment]
Now I judge by first line. But `all lines are commented` seems good predicate

**Comment by dglent** [comment]
I installed the latest git version and i cannot use this feature with Ctrl+U, what is the right usage ?

**Comment by hlamer** [comment]
Just press Ctrl+U. Which language are you coding? Post a sample here

**Comment by dglent** [comment]
Yes it works in python files
I have tried in a rpm spec file to commented the lines
