### ISSUE TITLE
New Line problems with when editing Ruby source code

### ISSUE THREAD

**Issue by rgb-one** [hlamer/enki#389]
Hey. When editing ruby code and the `RETURN` key is pressed to go to a new line, there is delay followed by extra indentation on the new line.

Here are some illustrations:

**Fig 1.**
![j6yroctows](https://cloud.githubusercontent.com/assets/5672238/12969943/cd635634-d055-11e5-9fd0-ff977c23d20e.gif)

**Fig 2.**
![htk2d3f5xx](https://cloud.githubusercontent.com/assets/5672238/12969953/e7293d22-d055-11e5-91b8-7e14687b6291.gif)

**Fig 3.**
![almesdwn7d](https://cloud.githubusercontent.com/assets/5672238/12969955/f6c505cc-d055-11e5-8997-1f77bf9c0249.gif)

This doesn't happen when working with Python code.

My platform is Windows 10 64-bit architecture.
Enki version is 15.11.1

**Comment by hlamer** [comment]
@rgb-one, Qutepart has [ruby indenter](https://github.com/hlamer/qutepart/blob/master/qutepart/indenter/ruby.py) and event [tests](https://github.com/hlamer/qutepart/blob/master/tests/test_indenter/test_ruby.py) for it. But the tests are broken and indenter seems to be working incorrectly.
It is difficult for me to test it because I don't code in ruby. But is seems like you do.
Your help is welcome!

**Comment by hlamer** [comment]
Tried to type this code samples on master Enki and Qutepart. Works for me. However ruby indenter contains some other bugs.
@rgb-one, post a code samples as a text if you are having problems on master.
Closing this issue, help from a ruby programmer still welcome.

**Comment by rgb-one** [comment]
Error persists on `master`. I tested on a flavor of Arch Linux. @hlamer you said you don't get this error on master? [Here] is the Ruby source code that I used, maybe that helps.

I will look into the Ruby indenter when I have less stuff to do.

[Here]:<https://gist.githubusercontent.com/rgb-one/66c6b11f2b8674902bae/raw/e75944de3b14f42eaae05ccfccde633caaeee667/mnemo>
